version: "3.8"
services:
  web:
    build:
      dockerfile: Dockerfile.development
    ports: ["3000:3000"]
    environment:
      DATABASE_URL: postgres://postgres:password@db/postgres
      BINDING: 0.0.0.0
    volumes:
      - .:/usr/local/src/app
    depends_on:
      - db
    command: ["sh", "-c", "bin/rails db:setup && exec bin/rails server"]
  db:
    image: postgres:14.4-alpine3.16
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
